const PatentFormDetails = [
  {
    id: "title",
    type: "text",
    name: "patent[title]",
    placeholder: "Title of Patent",
    required: true,
  },
  {
    id: "inventors",
    type: "text",
    name: "patent[inventors]",
    placeholder: "Patent Creator(s)",
    required: true,
  },
  {
    id: "applicationNo",
    type: "number",
    name: "patent[applicationNo]",
    placeholder: "Application Number",
    required: false,
  },
  {
    id: "subjectCategory",
    type: "text",
    name: "patent[subjectCategory]",
    placeholder: "Enter Category",
    required: true,
  },
  {
    id: "filingDate",
    type: "date",
    name: "patent[filingDate]",
    placeholder: "Filing Date",
    required: true,
  },
  {
    id: "publicationDate",
    type: "date",
    name: "patent[publicationDate]",
    placeholder: "Publication Date",
    required: true,
  },
  {
    id: "volume",
    type: "text",
    name: "patent[volume]",
    placeholder: "Enter Volume",
    required: false,
  },
  {
    id: "editor",
    type: "text",
    name: "patent[editor]",
    placeholder: "Enter Editor Name",
    required: false,
  },
  {
    id: "publisher",
    type: "text",
    name: "patent[publisher]",
    placeholder: "Enter Publisher Name",
    required: false,
  },
  {
    id: "pageNo",
    type: "text",
    name: "patent[pageNo]",
    placeholder: "Enter page No",
    required: false,
  },
  {
    id: "url",
    type: "text",
    name: "patent[url]",
    placeholder: "Enter URL",
    required: false,
  },
];

export default PatentFormDetails;
