const PatentFormDetails = [
  {
    id: "title",
    type: "text",
    name: "patent[title]",
    placeholder: "Title of Publication",
    required: true,
  },
  {
    id: "author",
    type: "text",
    name: "patent[author]",
    placeholder: "Enter Author",
    required: true,
  },
  {
    id: "publishedMedia",
    type: "text",
    name: "patent[publishedMedia]",
    placeholder: "Enter Journal/Book Title ",
    required: false,
  },
  {
    id: "doi",
    type: "date",
    name: "patent[doi]",
    placeholder: "Enter DOI",
    required: true,
  },
  {
    id: "year",
    type: "number",
    name: "patent[year]",
    placeholder: "Year of Publication",
    required: true,
  },
  {
    id: "subject",
    type: "text",
    name: "patent[subject]",
    placeholder: "Subject Type",
    required: true,
  },
  {
    id: "volume",
    type: "text",
    name: "patent[volume]",
    placeholder: "Enter Volume",
    required: false,
  },
  {
    id: "editor",
    type: "text",
    name: "patent[editor]",
    placeholder: "Enter Editor Name",
    required: false,
  },
  {
    id: "publisher",
    type: "text",
    name: "patent[publisher]",
    placeholder: "Enter Publisher Name",
    required: false,
  },
  {
    id: "pageNo",
    type: "text",
    name: "patent[pageNo]",
    placeholder: "Enter page No",
    required: false,
  },
  {
    id: "url",
    type: "text",
    name: "patent[url]",
    placeholder: "Enter URL",
    required: false,
  },
];

export default PatentFormDetails;
